{{- if .Values.worker.enabled }}
{{- $root := . -}}
{{- range $queueName, $workerConfig := $root.Values.worker.queues -}}
{{- $mergedWorkerConf := mustMergeOverwrite (dict) $root.Values.worker $workerConfig -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "suse.authentik.worker.fullname" (dict
    "context" $root
    "workerConfig" $mergedWorkerConf
  )
  }}
  namespace: {{ include "authentik.namespace" $root | quote }}
  labels:
    {{- include "authentik.labels" (dict "context" $root "component" $mergedWorkerConf.name) | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy $root.Values.global.deploymentAnnotations) $mergedWorkerConf.deploymentAnnotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key}}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- with include "authentik.strategy" (mergeOverwrite (deepCopy $root.Values.global.deploymentStrategy) $mergedWorkerConf.deploymentStrategy) }}
  strategy:
    {{- trim . | nindent 4 }}
  {{- end }}
  {{- if not $mergedWorkerConf.autoscaling.enabled }}
  replicas: {{ $mergedWorkerConf.replicas }}
  {{- end }}
  revisionHistoryLimit: {{ $root.Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "authentik.selectorLabels" (dict "context" $root "component" $mergedWorkerConf.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authentik.labels" (dict "context" $root "component" $mergedWorkerConf.name) | nindent 8 }}
        {{- with (mergeOverwrite (deepCopy $root.Values.global.podLabels) $mergedWorkerConf.podLabels) }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/secret: {{ include (print $root.Template.BasePath "/secret.yaml") $root | sha256sum }}
        {{- with (mergeOverwrite (deepCopy $root.Values.global.podAnnotations) $mergedWorkerConf.podAnnotations) }}
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      {{- with $mergedWorkerConf.imagePullSecrets | default $root.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $mergedWorkerConf.serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- with $mergedWorkerConf.automountServiceAccountToken }}
      automountServiceAccountToken:  {{ . }}
      {{- end }}
      {{- else }}
      {{- if $root.Values.serviceAccount.create }}
      serviceAccountName: {{ include "authentik-remote-cluster.fullname" .Subcharts.serviceAccount }}
      {{- end }}
      {{- end }}
      {{- with $root.Values.global.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (mergeOverwrite (deepCopy $root.Values.global.securityContext) $mergedWorkerConf.securityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $mergedWorkerConf.priorityClassName | default $root.Values.global.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- if $mergedWorkerConf.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ $mergedWorkerConf.terminationGracePeriodSeconds }}
      {{- end }}
      {{- with $mergedWorkerConf.initContainers }}
      initContainers:
        {{- tpl (toYaml . ) $ | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ $mergedWorkerConf.name }}
          image: {{ default $root.Values.global.image.repository $mergedWorkerConf.image.repository }}:{{ default (include "authentik.defaultTag" $root) $mergedWorkerConf.image.tag }}{{- if (default $root.Values.global.image.digest $mergedWorkerConf.image.digest) -}}@{{ default $root.Values.global.image.digest $mergedWorkerConf.image.digest }}{{- end }}
          imagePullPolicy: {{ default $root.Values.global.image.pullPolicy $mergedWorkerConf.image.pullPolicy }}
          {{- $args := default (list "worker") $mergedWorkerConf.args }}
          args:
            {{- $args | toYaml | nindent 12 }}
          env:
            {{- with (concat $root.Values.global.env $mergedWorkerConf.env) }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: AUTHENTIK_LISTEN__HTTP
              value: {{ printf "0.0.0.0:%v" $mergedWorkerConf.containerPorts.http | quote }}
            - name: AUTHENTIK_LISTEN__METRICS
              value: {{ printf "0.0.0.0:%v" $mergedWorkerConf.containerPorts.metrics | quote }}
          envFrom:
            - secretRef:
                name: {{ template "authentik.secret.name" $root }}
            {{- with (concat $root.Values.global.envFrom $mergedWorkerConf.envFrom) }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if or $root.Values.geoip.enabled $root.Values.global.volumeMounts $mergedWorkerConf.volumeMounts $root.Values.blueprints.configMaps $root.Values.blueprints.secrets }}
          volumeMounts:
            {{- with $root.Values.global.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with $mergedWorkerConf.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if $root.Values.geoip.enabled }}
            - name: geoip-db
              mountPath: /geoip
            {{- end }}
            {{- range $name := $root.Values.blueprints.configMaps }}
            - name: blueprints-cm-{{ $name }}
              mountPath: /blueprints/mounted/cm-{{ $name }}
            {{- end }}
            {{- range $name := $root.Values.blueprints.secrets }}
            - name: blueprints-secret-{{ $name }}
              mountPath: /blueprints/mounted/secret-{{ $name }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ $mergedWorkerConf.containerPorts.http }}
              protocol: TCP
            - name: metrics
              containerPort: {{ $mergedWorkerConf.containerPorts.metrics }}
              protocol: TCP
          {{- with $mergedWorkerConf.livenessProbe }}
          livenessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $mergedWorkerConf.readinessProbe }}
          readinessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $mergedWorkerConf.startupProbe }}
          startupProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $mergedWorkerConf.resources | nindent 12 }}
          {{- with $mergedWorkerConf.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $mergedWorkerConf.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if $root.Values.geoip.enabled }}
        - name: geoip
          image: {{ $root.Values.geoip.image.repository }}:{{ $root.Values.geoip.image.tag }}{{- if $root.Values.geoip.image.digest -}}@{{ $root.Values.geoip.image.digest }}{{- end }}
          imagePullPolicy: {{ $root.Values.geoip.image.pullPolicy }}
          env:
            {{- with $root.Values.geoip.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: GEOIPUPDATE_FREQUENCY
              value: {{ $root.Values.geoip.updateInterval | quote }}
            - name: GEOIPUPDATE_PRESERVE_FILE_TIMES
              value: "1"
            {{- if not $root.Values.geoip.existingSecret.secretName }}
            - name: GEOIPUPDATE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "authentik.fullname" . }}
                  key: GEOIPUPDATE_ACCOUNT_ID
            - name: GEOIPUPDATE_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "authentik.fullname" . }}
                  key: GEOIPUPDATE_LICENSE_KEY
            {{- else }}
            - name: GEOIPUPDATE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $root.Values.geoip.existingSecret.secretName }}
                  key: {{ $root.Values.geoip.existingSecret.accountId }}
            - name: GEOIPUPDATE_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $root.Values.geoip.existingSecret.secretName }}
                  key: {{ $root.Values.geoip.existingSecret.licenseKey }}
            {{- end }}
            - name: GEOIPUPDATE_EDITION_IDS
              value: {{ required "geoip edition id required" $root.Values.geoip.editionIds | quote }}
          {{- with $root.Values.geoip.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- with $root.Values.geoip.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: geoip-db
              mountPath: /usr/share/GeoIP
          resources:
            {{- toYaml $root.Values.geoip.resources | nindent 12 }}
          {{- with $root.Values.geoip.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- with $mergedWorkerConf.extraContainers }}
          {{- tpl (toYaml . ) $ | nindent 8 }}
        {{- end }}
      {{- with include "authentik.affinity" (dict "context" $root "component" $mergedWorkerConf) }}
      affinity:
        {{- trim . | nindent 8 }}
      {{- end }}
      {{- with $mergedWorkerConf.nodeSelector | default $root.Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $mergedWorkerConf.tolerations | default $root.Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $mergedWorkerConf.topologySpreadConstraints | default $root.Values.global.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
      - {{ toYaml $constraint | nindent 8 | trim }}
        {{- if not $constraint.labelSelector }}
        labelSelector:
          matchLabels:
            {{- include "authentik.selectorLabels" (dict "context" $ "component" $mergedWorkerConf.name) | nindent 12 }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- if or $root.Values.geoip.enabled $root.Values.global.volumes $mergedWorkerConf.volumes $root.Values.blueprints.configMaps $root.Values.blueprints.secrets }}
      volumes:
      {{- with $root.Values.global.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $mergedWorkerConf.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $root.Values.geoip.enabled }}
        - name: geoip-db
          emptyDir: {}
      {{- end }}
      {{- range $name := $root.Values.blueprints.configMaps }}
        - name: blueprints-cm-{{ $name }}
          configMap:
            name: {{ $name }}
      {{- end }}
      {{- range $name := $root.Values.blueprints.secrets }}
        - name: blueprints-secret-{{ $name }}
          secret:
            secretName: {{ $name }}
      {{- end }}
      {{- end }}
      enableServiceLinks: true
      {{- if $mergedWorkerConf.hostNetwork }}
      hostNetwork: {{ $mergedWorkerConf.hostNetwork }}
      {{- end }}
      {{- with $mergedWorkerConf.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $mergedWorkerConf.dnsPolicy }}
      dnsPolicy: {{ $mergedWorkerConf.dnsPolicy }}
      {{- end }}
...
{{ end -}}
{{- end }}
